#!/bin/sh

# programs to run
riverctl spawn 'swaybg -m fill -i "$HOME"/.local/share/backgrounds/wall'
riverctl spawn yambar
riverctl spawn 'emacs --daemon'
riverctl spawn dunst

# rivertile
riverctl spawn 'rivercarro -main-ratio 0.67 -main-location right -inner-gaps 12 -outer-gaps 12'
riverctl default-layout rivercarro

# [config]
riverctl focus-follows-cursor normal

riverctl border-color-focused 0xD79921
riverctl border-color-unfocused 0x282828
riverctl border-width 1

riverctl set-repeat 50 300

# [mappings]
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# printScrn = screenshot entire screen
# shift+printScrn = screenshot selection
# alt+printScrn = screenshot view (unsupported in river)
# uses my custom screenshot script
riverctl map normal None Print spawn 'screenshot'
riverctl map normal Mod1 Print spawn 'screenshot -f'
riverctl map normal Shift Print spawn 'screenshot -a'

riverctl map normal Mod4+Shift f toggle-fullscreen
riverctl map normal Mod4+Shift Space toggle-float

riverctl map -repeat normal Mod4 l focus-view previous
riverctl map -repeat normal Mod4 h focus-view next
riverctl map -repeat normal Mod4 s zoom

riverctl map normal Mod4+Shift q exit
riverctl map normal Mod4+Shift c close

riverctl map -repeat normal Mod4 Return spawn "foot"
riverctl map normal Mod4+Shift e spawn "emacsclient -c"

riverctl map normal Mod4 d spawn "yofi binapps"
riverctl map normal Mod4 p spawn "passmenu"

# mappings per tag
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map -repeat normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map -repeat normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map -repeat normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map -repeat normal Super+Shift+Control $i toggle-view-tags $tags
done

# volume
for mode in normal locked
do
    riverctl map $mode Mod4 Space spawn "mpc toggle"
    riverctl map -repeat $mode Mod4 bracketleft spawn "amixer sset Master 2%-"
    riverctl map -repeat $mode Mod4 bracketright spawn "amixer sset Master 2%+"
done
