colorscheme base16-gruvbox-dark-hard
add-highlighter global/ number-lines -relative -hlcursor -min-digits 2
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -tab '›' -lf ' ' -spc ' '
add-highlighter global/ wrap -width 80

set global indentwidth 0
set global tabstop 4

map global user y '<a-|>xsel -b <ret>' -docstring 'copy to system clipboard'
map global user p '|xsel -b <ret>' -docstring 'paste from system clipboard'
map global user | '<a-|>' -docstring 'pipe to'
map global normal '#' ': comment-line <ret>'
