keys:
  - &user age13u4wfjugnvj8wwer3w3q6p9q56w6sz95fqqdwsfwa8yj60x34f3s3hrs6l
  - &xray age1wxy6vkca6sy4fsgvq49fs2etet5xctmzygtadlp2rx09zrjjruxst2phar
creation_rules:
  - path_regex: secrets/xray\.yaml$
    key_groups:
    - age:
      - *xray
      - *user
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user
