bar:
  height: 18
  location: bottom
  background: 282828ff
  foreground: ebdbb2ff
  layer: "top"

  font: "Fantasque Sans Mono:pixelsize=14:antialias=true:autohint=true"

  left:
    - river:
        title: {string: {max: 50, margin: 10, text: "{title}" }}
        content:
          map:
            tag: focused
            values:
              false:
                map:
                  tag: occupied
                  values:
                    false: {empty: {}}
                    true:
                      string:
                        text: " {id} "
              true: {string: {text: "[{id}]"}}

  center:
    - clock:
        date-format: "%a, %d %b %Y"
        content:
          - string: {right-margin: 3, text: "{time} {date}"}

  right:
    - mpd:
        host: "/run/user/1000/mpd/socket"
        content:
          - string:
              left-margin: 5
              max: 30
              text: "{artist} - "
          - string:
              max: 30
              text: "{title} "
          - string:
              right-margin: 5
              max: 30
              text: "[{album}]"
          - progress-bar:
              tag: "elapsed"
              length: 20
              start: {string: {text: "["}}
              end: {string: {text: "]"}}
              fill: {string: {text: "#"}}
              empty: {string: {text: "-"}}
              indicator: {string: {text: ">"}}
    - alsa:
        card: "default"
        mixer: "Master"
        content:
          - map:
              tag: "online"
              values:
                false: {empty: {}}
                true:
                  string:
                    margin: 5
                    text: "{percent}%"
