* In love with an Emacs
Wilbur Soot "In love with an e-girl" parody  
https://www.youtube.com/watch?v=YbYJKGWrG7U  

Well it's 2:45 PM  
Wake up from snoring, boot up EM  
CTRL pedal (under desk)  
Linux boots  
vim is dead  

what's poppiiiiiiiing  
WHAT'S POPPIIIIIIIING  

it's beauty  
it's grace  
ten thousand packages for this gorgeous interface  
Just a single, package more  
Sends it rubbing up my ethernet chord  


I wanna be the guy  
That falls asleep, *debugging* elisp  
I'll make it behave  
Just like i  fucking wanted  
cos i like it  
and it likes my attention  
let's skip to the good bit  
let's configurate our emacs application  

i'm in love with an  
i'm in love with an  
i'm in love with an  
with an e-macs  

i'm in love with an  
i'm in love with an  
i'm in love with an  
with an e-macs  

VIM JUST DOESN'T FUCKING WORK  
It can't even display a simple clock  

I am not stupid, i am completely retarded  


Did you know i also have high blood pressure  
self-diagnosed though, i should mension  

i thought.  
emacs could be the one to fix it  
(it just gave me carpal tunnel lol)  


i wanna be the lisp  
that you fall on sleep debugging  
meanwhile i'll  
find other people to write me  
cos you. like. me.  
and i think you're a maniac  
let's get to the good bit  
let's completely block all contact  


i'm in love with an  
i'm in love with an  
i'm in love with an  
with an e-macs  

i'm in love with an  
i'm in love with an  
i'm in love with an  
with an e-macs  

vim just doesn't fucking work  
i've said it so many times before  
how could i live on  
if i keep on collecting?!  
EVERY LITTLE BUG AND INPERFECTION  
constant pain in EVERY direction  
my pinkie weeps  
disbelief heads suspensions  


i wanna be the guy  
that uninstalls this application  
10G of emacs files  
i seek medical attention  
cos i base my  
configs on obsessive media  
maybe if i act like them  
i'll configure  
my EM  
